### ISSUE TITLE
dokładność numeryczna

### ISSUE THREAD

**Issue by pbiecek** [tzoltak/zadaniaRegresja#7]
W zadaniu piątym [linie 396-397
          args$content$par_hisei,
          zadaniaRegresja::answers[[5]]
)
sprawdzana jest identyczność liczb, w moim rozwiązaniu okazało się, że wyniki są zaokrąglana do siódmej cyfry (to raczej sprawka as.data.frame)
w www liniach najlepiej testować różność rozwiązań z zaokrągleniem, np. do dwóch cydr po kropce

**Comment by tzoltak** [comment]
Od strony kodu "nieszyfrowanego", to właśnie dodaję explicite podaną w wywołaniu all.equal() liberalną wartość argumentu `tolerance`.
